# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v4.2
      - name: GitHub Actions Status Embed for Discord
        uses: SebastiaanZ/github-status-embed-for-discord@v0.3.0
        with:
            webhook_id: '819318289729323010'  # Has to be provided as a string
            webhook_token: ${{ secrets.webhook_token }}
            status: 'success'
            pr_author_login: ${{ github.event.pull_request.user.login }}
            pr_number: ${{ github.event.pull_request.number }}
            pr_title: ${{ github.event.pull_request.title }}
            pr_source: ${{ github.event.pull_request.head.label }}
            issue_author_login: ${{ github.event.issue.user.login }}
            issue_number: ${{ github.event.issue.number }}
            issue_title: ${{ github.event.issue.title }}
            issue_status: ${{ github.event.issue.state }}



